name: Deploy Infraestructura con Terraform

# Se ejecuta en push a la rama Infra o al crear un pull request
on:
  push:
    branches:
      - Infra
  pull_request:
    branches:
      - Infra

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Fmt
        working-directory: infra
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/Infra'
        working-directory: infra
        run: terraform apply -auto-approve tfplan

  site:
    needs: terraform
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Infra'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sincronizar sitio con S3
        run: |
          aws s3 sync ./site s3://${{ secrets.S3_BUCKET_NAME }} --delete
